### ISSUE TITLE
OpenCollective or similar

### ISSUE THREAD

**Issue by ffMathy** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#100]
@notanengineercom I think we should create an OpenCollective site where people can support this project. That would also make it easier for me to reserve time for it.

And then I think we should somehow figure out how to distribute the funds. You have almost already contributed more to this project than I have, so of course you should receive at least half of the support.

What do you think? Do you have any experiences with these things?

**Comment by notanengineercom** [comment]
I think that's a great idea, thanks a lot for including me!
I have no experiences with this at all, but I'm happy to help out on creating it! What would be the first steps?

**Comment by ffMathy** [comment]
@notanengineercom I have created the project now. However, I somehow need your e-mail address to add you as an admin there, and I have no idea how on earth we're going to do that without you revealing your e-mail to the entire world :sweat_smile:

**Comment by notanengineercom** [comment]
haha I just sent you an email!

**Comment by ffMathy** [comment]
Alright, you should be invited now! Check your email :D

Perhaps we should have something in the README.md file, allowing for people to contribute. Perhaps an OpenCollective badge? What do you think?


Fra: Enrique Pöhlmann<mailto:notifications@github.com>
Sendt: 14. april 2020 13:37
Til: ffMathy/FluffySpoon.JavaScript.Testing.Faking<mailto:FluffySpoon.JavaScript.Testing.Faking@noreply.github.com>
Cc: Mathias Lykkegaard Lorenzen<mailto:mathias.lorenzen@live.com>; Author<mailto:author@noreply.github.com>
Emne: Re: [ffMathy/FluffySpoon.JavaScript.Testing.Faking] OpenCollective or similar (#100)


haha I just sent you an email!

**Comment by notanengineercom** [comment]
resolved
