### ISSUE TITLE
Overloaded function signature with a Promise will not provide .resolves().

### ISSUE THREAD

**Issue by elAndyG** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#101]
Using the Calculator example as a class, If i were to overload a method that is a promise with a void, it will not provide a resolve() method.
~~
```js
class Calculator {
  heavyOperation(): Promise<number> | void {
    const a = 2;
  }
}
```
~~
In the section for "Working with Promises" I can no longer do a `.resolves()`
```js
    const sub = Substitute.for<Calculator>();
    sub.heavyOperation().resolves(); //<-- resolves does not exist
```

Error

> Property 'resolves' does not exist on type '(void & { returns: (...args: (void | Promise<number>)[]) => void; throws: (exception: any) => never; } & { mimicks: (func: () => void | Promise<number>) => void; }) | (void & { ...; } & { ...; } & { ...; }) | (Promise<...> & ... 1 more ... & { ...; }) | (Promise<...> & ... 2 more ... & { ...; })'.

Is there an alternative approach to accessing the `.resolves()` or if this would be a feature request?

(Updated request)

**Comment by notanengineercom** [comment]
Hey! Is the signature of the function `() => Promise<number> | void` or `(a: number, b: number) => Promise<number> | void`? I think as a temporal workaround you could use `.returns(Promise.resolve(123)` while we investigate this 😁

**Comment by elAndyG** [comment]
Ah, let me update my example. What i'm seeing is when a class has an overloaded operation. Sorry about the poor quality above... it t works well with an interface, just not a class..
```typescript
class Calculator2 {
  heavyOperation(): Promise<number> | void {
    const a = 2;
  }
}

describe('My Test', () => {
  it('test this"', () => {
    const sub = Substitute.for<Calculator2>();
    sub.heavyOperation().resolves(); //<-- resolves does not exist
  });
});
```

**Comment by notanengineercom** [comment]
@elAndyG I wasn't able to find an obvious solution for this issue. The distributive nature of the type is somehow not being propagated... I think it disappears when combining union with intersection types... As I said in the first comment, you can solve your issue with `.returns`.

`sub.heavyOperation().returns(Promise.resolve(123))` in the case you want to return the number promise. In the case of the void return type, as it's not a promise, `sub.heavyOperation().returns()` is the only and correct way to return void (in your function signature).

**Comment by notanengineercom** [comment]
I'll close this in 2 days if there's no more activity

**Comment by elAndyG** [comment]
@notanengineercom  I’ll see if I can come up with a solution and submit a PR for it. For now, I created a facade for the piece in question and that keeps the caller unique. Aside from that, I’m very happy with the framework! 👍🏻👍🏻

**Comment by notanengineercom** [comment]
Awesome, thanks for the support 😄
