### ISSUE TITLE
Arg.is predicate type should match specified generic type

### ISSUE THREAD

**Issue by psxvoid** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#106]
Is there a reason why `Arg.is<MyType>`  is `any` inside the callback? It feels like we are missing a hand from typescript here - it can verify **strongly typed** arguments and give a compile-time error. With `any` argument type typescript is useless and we won't receive a compile-time error, for example on misspelled property.

Here is how type definition looks like right now:
```ts
static is<T>(predicate: (input: any) => boolean): Argument<T> & T;
```

and here is how it "should" look like (possibly):
```ts
static is<T>(predicate: (input: T) => boolean): Argument<T> & T;
```

**Comment by notanengineercom** [comment]
No reason at all! I just checked locally, all types and tests still behaving correctly.
I also enhanced the Arg.all() to adapt to the arguments types. Closing this as pr is up.
Thanks for the feedback 😄
