### ISSUE TITLE
ng test succeeds, but IDE complains

### ISSUE THREAD

**Issue by troywweber7** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#12]
I am using the PhpStorm IDE put out by IntelliJ and when I run `ng test`, compilation succeeds, but in the IDE I get the following:

![image](https://user-images.githubusercontent.com/4765979/47537555-3d8c9300-d87b-11e8-8c7e-5e46df18ca26.png)

This is an Angular 7 project (which uses TypeScript 3). Any ideas why this builds fine but fails the IDE inspection?

**Comment by ffMathy** [comment]
Does PhpStorm even support TypeScript 3? I know that ReSharper, a similar tool by JetBrains only supports 2.8 or something.

What happens if you open it in Visual Studio Code?

**Comment by troywweber7** [comment]
@ffMathy I'm looking into it, but that strikes a bell and I think that might be the issue... They will pick up any TypeScript version installed but I suspect that inspections installed by a plugin are not yet at TypeScript 3...
