### ISSUE TITLE
useful error messages

### ISSUE THREAD

**Issue by troywweber7** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#13]
The mocking works great, but within a framework like Jasmine, is there any way to get a useful error string? e.g. when `mock.received(1).someFunction(1,2)` is false, an error like "expected someFunction(1,2) to be called once, but it was called 3 times" would be nice. Is this feature already here and I'm just missing it?

**Comment by troywweber7** [comment]
I rescind. Slightly. Turns out it does throw a message.

`mock.received(1).someFunction(1,2)`

throws the following

```
Error: Expected 2 calls to the method set with arguments [[object Object]], but received 1 of such call.
All calls received to method set:
-> 1 call with arguments [[object Object]]
```

It might be better if `[[object Object]]` was stringified or inspected to provide better information.

**Comment by ffMathy** [comment]
There is a dilemma though. We have to handle stringifying the parameters also if they contain circular references.

We would have to make a custom serialization function. Unless you have a way to do it? 

Totally worth it though. Thanks for the feedback! Awaiting your reply.

**Comment by troywweber7** [comment]
I misspoke when I suggested stringifying. Just use `util.inspect(obj)`.

![image](https://user-images.githubusercontent.com/4765979/47584312-db7d6d80-d90e-11e8-9476-74f48ab04c5c.png)

**Comment by ffMathy** [comment]
Ah very nice! I'll implement that soon. I'm not sure I will have much time over the next couple of days though, but if you are interested in making the change, it is currently located in `Utilities.ts`. Should be fairly simple.

**Comment by ffMathy** [comment]
This has now been implemented. Better late than never.
