### ISSUE TITLE
`JSON.stringify()` does not play well

### ISSUE THREAD

**Issue by AuHau** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#138]
**Describe the bug**
When calling `JSON.stringify` on Substitute I will receive `undefined`. While I understand that it is hard to decide what should be returned I would expect at least something and not `undefined`.

I think that the `toJSON()` function could be employed here to define some behavior.

**To Reproduce**
```typescript
interface Obj {
	hello: string
}
const sub = Substitute.for<Obj>()
sub.hello.returns('world')
JSON.stringify(sub) // undefined
```

**Comment by notanengineercom** [comment]
I was able to reproduce it. Makes sense 👍 
Thanks for the report!
