### ISSUE TITLE
objects as arguments should allow for deep-matching

### ISSUE THREAD

**Issue by troywweber7** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#14]
It seems like I should be able to do something like

```
const input = { updateData: { update: 'data' } as any };
setPageLayout(pageLayout, input);
expect(pageLayout.received(1).set({ update: 'data' })).toBeTruthy();
```

but instead I'm cheating by doing something like

```
const input = { updateData: 'updateData' as any };
setPageLayout(pageLayout, input);
expect(pageLayout.received(1).set('updateData')).toBeTruthy();
```

**Comment by ffMathy** [comment]
Simply just remove the expect call. The received function will throw an exception if it didn't receive anything, so you don't need the expect and/or tobetruthy call.

If you still think it's worth it, I'll reconsider adding it. Awaiting your reply.

**Comment by troywweber7** [comment]
@ffMathy the main issue here is that there does not appear to be any deep matching available, or I just don't know the syntax for it.

Here is a side-by-side comparison of `typemoq` and `substitute` for the same exact test.

```typescript
const pageLayout1 = Mock.ofType<Excel.PageLayout>();
const pageLayout2 = Substitute.for<Excel.PageLayout>();

it('should call set on the pageLayout object if updateData field is provided', done =>
{
	const input = { updateData: { update: 'data' } as any };

	expect(() => setPageLayout(pageLayout1.object, input)).not.toThrow();
	pageLayout1.verify(x => x.set({ update: 'data' } as any), Times.exactly(1));

	expect(() => setPageLayout(pageLayout2, input)).not.toThrow();
	pageLayout2.received(1).set({ update: 'data' } as any);

	done();
});
```

Substitute throws because it is not deep matching the objects.

Thrown message:
```typescript
Error: Expected 1 call to the method set with arguments [[object Object]], but received none of such calls.
All calls received to method set:
-> 1 call with arguments [[object Object]]
```

Usually languages have a "deep" keyword that allows the user to choose whether exact matching or deep-matching is used.

NOTE: as I discuss in #13, that thrown message would be a bit more useful if those objects were inspected... I'lll go comment on that now...

**Comment by ffMathy** [comment]
This should be resolved now.

**Comment by felipe-augusto** [comment]
@ffMathy We are also having this problem, there's a way to perform a deep-equal comparison? Using the same example as before:

```js
const page = Substitute.for<Excel.PageLayout>();

it('should call set on the pageLayout object if updateData field is provided', () => {
  const input = { updateData: { update: 'data' }};

  setPageLayout(page, input)
  page.received(1).set({ update: 'data' });
});
```

It throws something like:

```sh
Error: Expected 1 call to the method set with arguments { update: 'data' } but received none of such calls.
All calls received to method set:
-> 1 call with arguments { update: 'data' }
```
