### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by jasperblues** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#16]
Excellent library. If you like, please upvote here: https://stackoverflow.com/questions/54489075/mock-classes-and-interfaces-fully-or-partially-in-typescript/54489092#54489092

(also shared info here: https://twitter.com/doctor_cerulean/status/1091230596414623744)

**Comment by lonix1** [comment]
It's very nice for those used to using professional tools, like, you know, what we're used to in .NET (e.g. NSubstitute). :wink: 

Amazing how much I miss that professionalism. Node is a mess, but this library makes it a little less so!

**Comment by lonix1** [comment]
BTW if you can find a way to integrate this library with [mocha-typescript](https://www.npmjs.com/package/mocha-typescript) then it would be 100% perfect.
