### ISSUE TITLE
Partial mock `this` in a mimick function is not the mock's `this` 

### ISSUE THREAD

**Issue by jasperblues** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#17]
*Steps to Repro:* 

* Create an interface:*

```
export interface Client {

    authorize(correlationId: string): Promise<string>;

    sendBuyerData(buyerId:string, correlationId: string): Promise<void>;

}
```

*Mock the authorize method: 

```
 const partialClient = Substitute.for<Client>();
 partialClient.sendBuyerData(Arg.all()).mimicks(client.sendBuyerData);
 partialClient.authorize(Arg.any()).returns(Promise.resolve(uuid()));
```

*Test:* 

```
 public async sendBuyerData(buyerId: string, correlationId: string): Promise<void> {

        const token = await this.authorize(correlationId);
        //etc 
```

*Expected:* 

This is the mock's this. 

*Actual:* 

This points to the function. A class's methods can't call other methods.

**Comment by ffMathy** [comment]
I'm not sure what you mean here. Can you elaborate - perhaps make a full reproducable example, throwing an error?

**Comment by jasperblues** [comment]
I mean when you partially mock a class, the concrete method should be able to call other methods in the mock. 

* For any concrete method, `this` doesn't point to the mock class. It points to the function. This can be fixed by binding the function to the mock. 

Expected: 

* A concrete method calls another method on the class, resulting in the mock's method being called. 

Actual: 

Error: Function does not have a property named `methodName` 

*Example:*

```typescript

```
class ClientDefaultImpl {

public async authorize(token: string): Promise<string> {} //THIS IS MOCKED 

public async sendBuyerData(buyerId: BuyerModel.Buyer['id'], correlationId: string): Promise<void> {

        logger.info(`Posting Buyer '${buyerId} to Unipay.'`);

        const token = await this.authorize(correlationId);   <---- This fails on a partial mock because `this` is not bound to the mock. 
        const unipayCustomerUrl = `${this.baseUrl}/api/customers`;

        // Fetch the buyer
        // etc more implementation

}
```

**Comment by jasperblues** [comment]
Please reopen this issue, it is an essential feature. I can send a pull request. Let me know if the example is not clear.

**Comment by ffMathy** [comment]
A PR would be absolutely fantastic.

I'm still not sure what you mean though. 

Can you provide an example with a unit test that fails?

**Comment by jasperblues** [comment]
OK, let's establish the problem with an example first. Stay tuned . . (it might take a few days, under the hammer here a bit, a the moment).

**Comment by ffMathy** [comment]
Closing until I hear more. Looking forward to it <3
