### ISSUE TITLE
Auto-verify mocks argument

### ISSUE THREAD

**Issue by hmvien** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#179]
**Is your feature request related to a problem? Please describe.**
It has become really cumbersome to define the mocks and then verify it later with `received()`. It would be nice for this check to happen while the test function is executing. Please take a look at the example from the README

```
// Create:
const calculator = Substitute.for<Calculator>();
 
// Set a return value:
calculator.add(1, 2).returns(3);
 
// Check received calls:
calculator.received().add(1, Arg.any());
```

If you replace the first call to `add()` with `calculator.add(2, 2).returns(3);`, the test will still pass. If `calculator.add()` is called with parameters that hasn't been registered a `Proxy` object is returned so it looks like there is already some checks here. Ideally I would like this to raise an error immediately instead of letting the test continue running.

**Describe the solution you'd like**
Instead of returning a `Proxy` object with parameter mismatch, an error should be thrown. This gets rid of the need to explicitly verifying the mock was invoked with `received()`. `received()` should still be used if you are interested in testing if a mock has been used. 

I would love to attempt to implement this in my of my weekends, but would love your thoughts to see if this is a feature that should be available.

Thanks

**Comment by notanengineercom** [comment]
Similar to https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/issues/165
Due to how js works, if we applied `Instead of returning a Proxy object with parameter mismatch, an error should be thrown`, setting a return value for `calculator.add(1, 2)` would throw said exception
