### ISSUE TITLE
Dynamic return value based on Object args

### ISSUE THREAD

**Issue by alexgoldstone** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#193]
I am looking for a method to mock functions that accept objects as parameters such that I can return a different response depending on specific object values.

My use-case is writing tests for API endpoints and mocking the framework's database query function.

For API endpoints that make only a single database request I can mock the return value for **any** parameters.

For API endpoints that make multiple requests this isn't so easy... the object passed to the database query function could be complex and I might know some of the values in the scope of the test but not enough to create a representation of the full object.

Since this library references NSubstitute as its inspiration I checked out its documentation to see if I could see how it might be done and see that with NSubstitute you can pass in a function... this would work but I'd need a way to access the parameters passed in so that a suitable response could be determined based on those parameters.

Something along the lines of:

```
databaseClient.query(Arg.any()).returns((args) => {
            // return something based on analysis (value, regex, etc.) of the args
});
```

If there is a better / alternative way to achieve this I'd greatly appreciate the guidance.

**Comment by notanengineercom** [comment]
Hi!
You could use the `mimicks` function instead of `returns` to get the callee arguments.
```typescript
databaseClient.query(Arg.any()).mimicks((propertyA, propertyB, propertyC) => {
            if (propertyA === 'foo') // do something
            // return something based on analysis (value, regex, etc.) of the args
});
```

If this isn't a solution for you, just reopen the issue and ping us 😄
