### ISSUE TITLE
Arg.is function called twice?

### ISSUE THREAD

**Issue by sticklerdev** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#22]
Here is a simple test:

import { Substitute, Arg } from '@fluffy-spoon/substitute';

type Addands = {
  op1: number;
  op2: number;
}

class RealCalculator {
  add(addands: Addands): number {
    return addands.op1 + addands.op2;
  }
}

let mockedCalculator = Substitute.for<RealCalculator>();
mockedCalculator.add(Arg.any()).returns(4);
const result = mockedCalculator.add({ op1: 1, op2: 2});
mockedCalculator.received(1).add(Arg.is(a => {
  console.log(a);
  return a.op1 === 1 && a.op2 === 2;
}));

When I run the above code, the _console.log(a)_ statement which prints the addands with which the _add_ function was called (line 18) in the parameter verification call is called twice. Am I doing something wrong?

Thanks.

**Comment by ffMathy** [comment]
Nope! This is definitely a bug. I'll get it fixed quite soon and add some tests to prevent the scenario in the future.

I might not have time until 2 weeks from now though. In the meanwhile, feel free to make a PR.

**Comment by ffMathy** [comment]
Thank you for your report! This has now been fixed. Release should be online in an hour or so.
