### ISSUE TITLE
Check received calls

### ISSUE THREAD

**Issue by thrixton** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#23]
Thanks for the library, it's great.

I've mimicked a method and now I'm trying to verify that it's been called, however, every time I call received(), it executes the method instead.

Is my understanding incorrect that it should just verify that the method has been executed the relevant number of times?

```ts
    const resultMock = Substitute.for<IResultService>();
    resultMock.objectResult(Arg.all()).mimicks((o, n, cb) => {
      // tslint:disable-next-line: no-unused-expression
      expect(o).to.be.instanceOf(ErrorResult);
      const eResult = o as ErrorResult;
      expect(eResult.validationErrors.length).to.equal(1);
    });

    container.unbind(TYPES.ResultService);
    container.bind<IResultService>(TYPES.ResultService).toConstantValue(resultMock);

    const service = container.get<IValidationService>(TYPES.ValidationService);

    const cbMock = Substitute.for<Callback>();
    // tslint:disable-next-line: no-unused-expression
    expect(service.handleValidationErrors(error, cbMock)).to.be.true;

    resultMock.received(1).objectResult(Arg.any(), Arg.any(), cbMock);
    // ^^^^ this results in another call to my mimicked function above
```

**Comment by ffMathy** [comment]
Yup! That's definitely a bug. Will get it fixed soon along with a unit test.

**Comment by ffMathy** [comment]
I can't reproduce the issue.

I made the following unit test which tried to reproduce - but it passes just fine.

Can you spot what I am doing wrong, and perhaps help make the test fit in your scenario?

https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/blob/9fccf088ec641a81baf5ac1005b98e18cb07965b/spec/issues/23.test.ts

**Comment by thrixton** [comment]
Thanks @ffMathy, I really appreciate your work.
I've sent a PR with the test modified.

**Comment by ffMathy** [comment]
Thanks! I'll have a look soon.

**Comment by thrixton** [comment]
Any idea when this might be looked at?
If you can point me in the right direction, I can have a look.
👍

**Comment by ffMathy** [comment]
I am very busy lately - but in 2 weeks or so it should be doable.

**Comment by domasx2** [comment]
hey, PR #30 fixes this
