### ISSUE TITLE
latest NPM release is 10 months old

### ISSUE THREAD

**Issue by narenchoudhary** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#237]
Thanks for this amazing package!

I see [v1.208.0 (10 months old) is still the latest available version on npm](https://www.npmjs.com/package/@fluffy-spoon/substitute?activeTab=versions), but the package has had lots of new merges since then.

As I needed `SubstituteOf<T>.clearSubstitute` had to use `2.0.0-beta.0` version (4 months old). 

I can also install directly from GitHub, but installing from npm is easier for tracking versions and helps with avoiding breaking changes.

Any reason we're not releasing on npm frequently? Anything we can help here with?

**Comment by notanengineercom** [comment]
👋 Hi!
Thanks for your interest. It's hard to maintain the lib on our free time, so we try to work on it whenever possible.
Regarding installing the beta version, you can install it via npm as [described here](https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/releases/tag/v2.0.0-beta.0).
```shell
npm i @fluffy-spoon/substitute@beta
```
