### ISSUE TITLE
Mocked method arguments not allowed when verifying method was called

### ISSUE THREAD

**Issue by jussimattila** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#24]
First of all, awesome library! Started looking at options for a new project yesterday and I'm already hooked.

I encountered one issue trying to verify that a method on a mock object has been called. I'm mocking `Aurelia` class from the [aurelia framework](https://aurelia.io). See the type definition here: https://github.com/aurelia/framework/blob/master/dist/aurelia-framework.d.ts#L35

Calling `setRoot(arg)` is allowed on the mock object but not when verifying that it has been called. The problem looks like this in my editor:
![image](https://user-images.githubusercontent.com/8625258/53867906-755fd000-3ffd-11e9-8d9b-dad1e53a1526.png)
![image](https://user-images.githubusercontent.com/8625258/53867922-7f81ce80-3ffd-11e9-87cd-f00fb7327982.png)

The two overloads for `setRoot()` visible in intellisense look like this:
![image](https://user-images.githubusercontent.com/8625258/53868024-b6f07b00-3ffd-11e9-9b18-dff174a36d19.png)
![image](https://user-images.githubusercontent.com/8625258/53868040-c2dc3d00-3ffd-11e9-850a-9b3d79709baa.png)

`Aurelia.setRoot(...)` doesn't really have overloads. But, the real one is not anymore available when calling `setRoot()` after `received()`: 
![image](https://user-images.githubusercontent.com/8625258/53868323-780ef500-3ffe-11e9-83a7-09e734d90497.png)

Do you happen to know what could cause this issue? 

Luckily, there is a workaround that allows the method to be called with an argument and the test to pass:
```
(aurelia.received(1) as Aurelia).setRoot("gui/suite-gui");
```

**Comment by ffMathy** [comment]
That's a bug, but I'm not sure TypeScript allows me to do anything about it. I'll look later today.

**Comment by ffMathy** [comment]
If you make the arguments required, what happens then?

If that works, does it help having them as required (without the `?` operator), but then with a default value?

**Comment by jussimattila** [comment]
Just making the argument required fixes the issue. But, since the declaration is not my code, I'm not going to edit it in reality. I'm okay with the workaround for now.

**Comment by aalpgiray** [comment]
any update on this one. I am getting this on sequelize methods.

**Comment by ffMathy** [comment]
Still investigating.

**Comment by aputinski** [comment]
Is this related to optional parameters not working not working when setting up a return?

```typescript
interface Foo {
  bar(path?: string): string;
}
let a = Substitute.for<Foo>();
a.bar(Arg.any()).returns("a"); // Property 'returns' does not exist on type 'string'.
```

**Comment by ulrichsg** [comment]
I've run into the same issue with the `Counter.inc()` method from https://www.npmjs.com/package/prom-client. In this case there are also two overloads, with one having a mandatory parameter and the other one having only optional parameters (https://github.com/siimon/prom-client/blob/master/index.d.ts#L183). The parameter I am passing is actually the mandatory one. Here's a minimal example:

```ts
import { Substitute } from '@fluffy-spoon/substitute';
import { Counter} from 'prom-client';

describe('Potential issue with received()', () => {
  it('fails with "TS2554: Expected 0 arguments, but got 1"', () => {
    const mockedCounter = Substitute.for<Counter>();
    mockedCounter.inc({ foo: 'bar' });
    mockedCounter.received(1).inc({ foo: 'bar' });
  });
});
```
