### ISSUE TITLE
call verification does not work when using Arg.all() to set up return values 

### ISSUE THREAD

**Issue by domasx2** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#25]
Hi,

Like the lib, but immediately hit a snag. Here's a minimal example:

```typescript
interface Calculator {
  add(a: number, b: number): number
}

const calc = Substitute.for<Calculator>()
calc.add(Arg.all()).returns(3)
calc.add(1, 2)
calc.add(2, 3)

// this passes just fine
calc.received().add(3, 4)
```

**Comment by ffMathy** [comment]
Woah, I'll see if I can reproduce. If I can, I'll write a test to prevent it.

This should definitely not happen. I'll verify and fix.

**Comment by ffMathy** [comment]
This has now been resolved, and will deploy in an hour at latest.

Thanks for making the library better!

**Comment by ffMathy** [comment]
Okay, it causes some other bugs. I'll revert and get back to the drawing board. I may not have time until in a week or so.

**Comment by domasx2** [comment]
Alright, looking forward  :) will try to find time to contribute perhaps

**Comment by domasx2** [comment]
I went over the codebase, and I see the problem: actual arguments the mock was called with are not recorded. I have idea how to refactor, will see if there's time over the weekend

**Comment by domasx2** [comment]
@ffMathy  I realised this broke ability to set up return values for different arguments eg
```typescript
const mock = substitute.for<Foo>
mock.bar(1).returns(2)
mock.bar(2).returns(3) // will fail, cause void is returned instead of proxy by bar(2)
```

Not sure how to solve it without changing api :(

**Comment by ffMathy** [comment]
Will revert soon tjen.

**Comment by ffMathy** [comment]
Do you have an idea of how to fix both scenarios?

**Comment by domasx2** [comment]
This is the best I could come up with: https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/pull/31

Still some limitations...
I'm now leaning towards writing smth that more resembles typemoq, just with more limited features and cleaner syntax

**Comment by ffMathy** [comment]
Very interesting! I'll have a look too next weekend or so.

Also, would you like to become a contributor on this repo?

**Comment by domasx2** [comment]
Nah, thanks, but I don't think I will continue working on this in the near future
