### ISSUE TITLE
Malformed package.json refers to Index.d.ts which does not exist in npm package - cannot use package

### ISSUE THREAD

**Issue by mz8i** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#32]
The npm package doesn't work. This is because the package.json has
```
"main": "dist/src/Index.js",
...
"typings": "./dist/src/Index.d.ts"
```
but the captial-letter `Index` files currently exist only in this github repo's `dist/` folder - they are nowhere to be found in the package obtained with `npm i -D @fluffy-spoon/substitute`. Presumably this is because of some renaming that occurred, after which the package.json didn't get updated. Really, it would be safer if this repo didn't have the transpilation result `dist/` folder committed - this would help avoid such errors.
The package.json needs to be corrected in order for npm users to be able to use the package at all.

**Comment by ffMathy** [comment]
Thanks for reporting this, it was introduced recently unfortunately.

I have fixed the issue. A new release will be up soon.
