### ISSUE TITLE
Add a type definition for Substitute.for<T> result?

### ISSUE THREAD

**Issue by mz8i** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#34]
Would it be possible to export a single type definition for the result of `Substitute.for`? This is so that it's easier to have mock variables in tests with proper type annotations, rather than needing to assign the value of `Substitute.for` in the place where the variable is declared. Especially useful for cases where the mock variable is defined for a whole test suite, and then it is being assigned to in beforeEach hooks or individual tests etc.

e.g.
```
import { Substitute, Mock} from '@fluffy-spoon/substitute';

let dependencyMock: Mock<DependencyClass>;

... more code

dependencyMock = Substitute.for<DependencyClass>();
```

I would presume it would be as easy as exporting
`export declare type Mock<T> = ObjectSubstitute<OmitProxyMethods<T>, T> & T;`

**Comment by ffMathy** [comment]
That's a great idea!

**Comment by testpossessed** [comment]
I agree it would be great to have an elegant option for this, but wonder if we couldn't just have Substitute inherit from ObjectSubstitute<OmitProxyMethods<T>, T> & T; and have the static Substitute.for<T> return an instance of Substitute<T>.  Feel free to tell me to shut up if TypeScript won't support this :-) 

Why?

I would prefer the library to stick with the philosophy of NSubstitute and avoid introducing terms like Mock, Stub etc into the code base.

**Comment by testpossessed** [comment]
I forked the repo and added a speculative attempt at providing a solution for this issue.

It is in a feature branch at https://github.com/testpossessed/FluffySpoon.JavaScript.Testing.Faking/tree/feature/return-substitute

Have a look, if you guys think it is appropriate I will submit as a PR.

I copied the compiled dist folder and pasted it over the contents of the package in in node_modules of my auto-barrel project and it works for me.

I added a new type *SubstituteOf<T>* and exported it along with the statics Substitute and Arg, which allowed me to do this.

```javascript
...
import { Substitute, Arg, SubstituteOf } from '@fluffy-spoon/substitute';
...

describe('AutoBarreller', () => {
    let configuration: SubstituteOf<IConfiguration>;
    let vsCodeApi: SubstituteOf<IVsCodeApi>;
    let utility: SubstituteOf<IUtility>;
    let exportStatementBuilder: SubstituteOf<IExportStatementBuilder>;
    let target: AutoBarreller;

    beforeEach(() => {
        configuration = Substitute.for<IConfiguration>();
        vsCodeApi = Substitute.for<IVsCodeApi>();
        utility = Substitute.for<IUtility>();
        exportStatementBuilder = Substitute.for<IExportStatementBuilder>();
        target = new AutoBarreller(configuration, vsCodeApi, utility, exportStatementBuilder);
    });

...
});

```

**Comment by ffMathy** [comment]
Looks fantastic! Make a PR, and I'll merge!

**Comment by testpossessed** [comment]
PR submitted
