### ISSUE TITLE
Is it possible to use Object.keys() with a Substitute.for() result?

### ISSUE THREAD

**Issue by mz8i** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#35]
I have a class which has a series of readonly properties, let's say
```
class A {
   public readonly foo: string;
   public readonly bar: number;

  constructor() {...}
}
```
I am trying to figure out a way to get the list of the names of A's properties at runtime, without actually constructing an instance of the class. I needed in a test, and I am already using Substititute.js so thought maybe I could use it here, but with no luck so far.
I tried `Object.keys(Substitute.for<A>())` but it returns an empty array. Any ideas if this can be done at all?

**Comment by ffMathy** [comment]
Can you show me the full code?

**Comment by mz8i** [comment]
```
import { Substitute } from '@fluffy-spoon/substitute';

class ApplicationConfig {
    //tslint:disable: no-unnecessary-field-initialization
    public readonly applicationName: string = undefined;
    public readonly environment: string = undefined;
    public readonly apiPort: number = undefined;
    public readonly logDirectory: string = undefined;

    constructor() {
        // CODE HERE REMOVED, READS VALUES FROM CONFIG BACKEND
    }

}

const mockConfig = Substitute.for<ApplicationConfig>();
const configKeys = Object.keys(mockConfig); // THIS ENDS UP EMPTY
```
Something like that.

**Comment by ffMathy** [comment]
Alright, well look at the compiled JavaScript file.

I think you'll find that there's not much chance for whoever is evaluating it to see what properties are available at runtime.

Perhaps you should look into TypeScript's `reflect-metadata` functionality.
