### ISSUE TITLE
Cannot convert object to primitive value

### ISSUE THREAD

**Issue by testpossessed** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#36]
I've been using the library for about a week as I started to re-factor a VS Code Extension I created.  For the most part Substitute is working as expected, but I have started to get an error "Cannot convert object to primitive value" when trying to verify a method call that returns a promise.  The promise may not be the issue, but I am getting the error in two places in one test suite while other similar calls in the same suite do not cause the error and the difference is what the target methods return.

I have pushed the current state of my code base to https://github.com/testpossessed/auto-barrel, in the hope someone can help me resolve the issue.

I am using Mocha with expect and the code base includes a Run Config that allows me to debug via the tests.  Using this I have traced the point where the issue occurs to the util.inspect call in the following function in Utilities.ts at line 7.  However I am struggling to see how to fix it or whether I am doing something wrong.

```
export function stringifyArguments(args: any[]) {
    args = args.map(x => util.inspect(x));
    return args && args.length > 0 ? 'arguments [' + args.join(', ') + ']' : 'no arguments';
};
```

The test file that this is happening in is https://github.com/testpossessed/auto-barrel/blob/master/src/test/unit/create-barrel-command.test.ts and the target of the test is https://github.com/testpossessed/auto-barrel/blob/master/src/create-barrel-command.ts

This is the setup part of the test
```
describe('CreateBarrelCommand', () => {
    const rootFolder = '\/c:\/barrel';
    const files: Array<string> = [
        '\/c:\/barrel\/test1.ts',
        '\/c:\/barrel\/test2.ts',
        '\/c:\/barrel\/test3.ts'
    ];
    const contentLines: Array<string> = [
        'export * from \'./test1\';',
        'export * from \'./test2\';',
        'export * from \'./test3\';'
    ];
    const barrelDetails = {barrelFilePath: `${rootFolder}/index.ts`, contentLines};

    let vsCodeApi: ObjectSubstitute<OmitProxyMethods<IVsCodeApi>, IVsCodeApi> & IVsCodeApi;
    let barrelBuilder: any;
    let target: CreateBarrelCommand;

    beforeEach(() => {
        vsCodeApi = Substitute.for<IVsCodeApi>();
        barrelBuilder = Substitute.for<IBarrelBuilder>();
        target = new CreateBarrelCommand(vsCodeApi, barrelBuilder);        
    });
```

There are a couple of helper functions that configure the substitutes that look like this

```
    function assumeVsCodeApiFindsFiles() {        
        vsCodeApi.findFiles(rootFolder).returns(Promise.resolve(files));
    }

    function assumeBarrelBuildReturnsResult(){
        barrelBuilder.build(Arg.all()).return(Promise.resolve(barrelDetails));
    }
```

I have focused on one test for now, which looks like this
```
     it.only('should fetch files via vs code api', async () => {
        assumeVsCodeApiFindsFiles();
        assumeBarrelBuildReturnsResult();

        await target.execute(rootFolder);

        // expect(
            vsCodeApi.received(1).findFiles(rootFolder); // this is where the error occurs
            // );
    });
```

My Mrs (she is also a very good developer) and I spent some time yesterday trying to resolve it but once we found where it happened we got stuck on what to do to solve it.

Any help in identifying either a fix or what I might be doing wrong would be greatly appreciated.

**Comment by testpossessed** [comment]
So i have been stepping into this call a bit further

```
args = args.map(x => util.inspect(x));
```

At this point x is a Proxy, which as util.inspect progress identifies as a Function (typeof x === 'function') and tries to format a string using a name property.  However the debugger shows there is no name property on Proxy and the error occurs.

Not sure how much help this is going to be, but it is some progress, I think.

**Comment by testpossessed** [comment]
Looking into util.inspect and found this on MDN

> The util.inspect() method returns a string representation of object that is intended for debugging. The output of util.inspect may change at any time and should not be depended upon programmatically.

**Comment by ffMathy** [comment]
Very interesting! Will look into it soon.

**Comment by ffMathy** [comment]
I haven't forgotten this, I just haven't had the time. Can you perhaps work on a PR for removing use of the inspect function?

**Comment by mpkelly** [comment]
This is causing me an issue with some async tests, too, so going to have to swap out Substitute for something else unfortunately.

**Comment by Nr9** [comment]
Same problem here.

**Comment by codeepic** [comment]
Same here - using `Substitute.for<interfaceName>()` works like a charm but sometimes I get `Cannot convert object to primitive value` and then I just have to mock the data. Also wasting a lot of time trying to figure out some logic behind why the error occurs or doesn't occur in very similar conditions.

**Comment by codeepic** [comment]
Is there any progress on this?

**Comment by testpossessed** [comment]
Not from my side, I opted to go a different route.  From my point of view the issue could be closed as it is not affecting me anymore, but will leave it open as others have expressed same issue.

**Comment by JamieCorkhill** [comment]
@testpossessed @ffMathy I'm really liking this tool, but I'm coming across the same issue. I'm also attempting to check if a mocked function was called with the correct values. Has there been any progress on this?

@codeepic Did you figure anything out?

Thanks.

**Comment by JamieCorkhill** [comment]
I really like Substitute and its fantastic syntax, but I, unfortunately, have to move to `ts-mockito`. I can try working on a PR when I have time (which might not be for a while) to explore the issue further and perhaps find an alternative for `util.inspect()` if you want @ffMathy.
