### ISSUE TITLE
Should the repository contain the dist/ folder?

### ISSUE THREAD

**Issue by mz8i** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#41]
It seems to me like not a best practice in general. Opens the project to the possibility of discrepancies between the TS code and what is actually released to npm. There was already issue #32 that stemmed from this. Besides it pollutes the commit diffs with stuff like .js.map files etc.

**Comment by ffMathy** [comment]
Nope, but if I add them to gitignore, they will also be ignored by NPM upon publishing.

**Comment by hmil** [comment]
@ffMathy Use a "`files`" entry in package.json to whitelist all the things you want included by npm. This way you can add the built files to .gitignore and still get them on npm.

https://docs.npmjs.com/files/package.json#files

**Comment by ffMathy** [comment]
Very cool @hmil - will check that out when I have time. In the meanwhile, PRs are welcome too!
