### ISSUE TITLE
Unexpected received behavior on uncalled method

### ISSUE THREAD

**Issue by abarre** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#44]
Testing an example based on the one in the README on the version `1.88.0`: 

```typescript
import { Substitute, Arg } from '@fluffy-spoon/substitute';

test('test substitute', () => {
  interface Calculator {
    add(a: number, b: number): number;
    subtract(a: number, b: number): number;
    divide(a: number, b: number): number;

    isEnabled: boolean;
  }

  // Create:
  const calculator = Substitute.for<Calculator>();

  // Set a return value:
  calculator.add(1, 2).returns(3);
  calculator.add(1, 2); // prints 3

  // Check received calls:
  calculator.received().add(1, Arg.any());
  calculator.didNotReceive().add(2, 2);
  
  // -> substract is never called, expecting an error here
  calculator.received().subtract(Arg.any(), Arg.any());
});
```
The test passes but it should not since `substract` is never called. It should fail at the line `calculator.received().subtract(Arg.any(), Arg.any());`

Note that this is the same if Calculator is a class or a abstract class.
I don't know if it's a bug or if I don't understand the API.

**Comment by notanengineercom** [comment]
For the exact same setup I get:
```typescript
Error: there is no mock for property: subtract
    at Context.handleNotFoundState (/Users/enrique/Documents/GitHub/FluffySpoon.JavaScript.Testing.Faking/src/Context.ts:58:15)
```

**Comment by vincentvanderweele** [comment]
Unrelated to this issue but a note to future readers arriving here by Googling "there is no mock for property" (for which this is the only hit):

> "there is no mock for property"

does not mean that there is something wrong with your mock. It means that _the mock has not been called_, so there is most likely something wrong with your code under test.

**Comment by ffMathy** [comment]
We should definitely fix the error message in that case. PRs are welcome.

**Comment by pr11me** [comment]
I guess a sensible message would be analogous to the case where the mock was called but with unexpected arguments. So here it would go sth like "Expected MyMock to be called with args (...) but no call received. Make sure your test code interacts with the mocked function".
If you could point me to the relevant places I could have a look :)
