### ISSUE TITLE
Received calls check should deep-compare arguments

### ISSUE THREAD

**Issue by MateusZitelli** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#48]
First, thanks for this amazing library!

I have being facing some issues when testing APIs that receive objects as arguments. Seems like the received call checks does not deep compare objects. Check out the example bellow:

```ts
it("it should get the correct object", async () => {
  const obj = {
    action: (value: { prop: string }) => `wow ${value.prop}`
  };

  const objMock = Substitute.for<typeof obj>();
  const arg = { prop: "wow" };
  
  objMock.action(arg);

  // This test passes
  objMock.received().action(arg);

  /* This fails with:
  Expected 1 or more calls to the method action2 with arguments [{ prop: 'wow' }], but received none of such calls.
    All calls received to method action2:
    -> call with arguments [{ prop: 'wow' }]
  */
  objMock.received().action({ prop: "wow" });
});
```

I believe a possible solutions would be the library to offer a way to deep-compare the arguments. Another solution would be a method to have access to the list of calls and arguments, so we can compare the arguments using for example Jest expect.

I am open for thoughts and suggestions.

**Comment by MainAero** [comment]
Your example should work when you are using `Arg.is`:

```js
import { Arg }  from '@fluffy-spoon/substitute';
import deepEqual from 'deep-equal';

...

it("it should get the correct object", async () => {
  const obj = {
    action: (value: { prop: string }) => `wow ${value.prop}`
  };

  const objMock = Substitute.for<typeof obj>();
  const arg = { prop: "wow" };
  
  objMock.action(arg);

  objMock.received().action(Arg.is(arg => deepEqual(arg, { prop: "wow" })));
});
```

**Comment by stephenh** [comment]
@MainAero true, but it seems like this should "just work" especially for object literals.

Granted, I understand maybe we don't want to assume _everything_ should be `deepEqual`'d, but AFAICT you can tell "is this a class instance or just an object literal" by doing something like:

```
if (Object.getPrototypeOf(thing) === Object.prototype) { 
  // this is very likely an object literal, so deepEqual it
} else {
  // this is probably a class instance
}
```

I.e.

```
Object.getPrototypeOf({ prop: "wow" }) === Object.prototype // true
Object.getPrototypeOf(someClassInstance) === Object.prototype // false
```

Given that, can fluffyspoon just do this for us, especially for object literals?

**Comment by Kosta-Github** [comment]
maybe the suggestion from @MainAero could be added as an additional method to `Arg`? something like this:
```
class Arg {
  ...
  isDeep(expected: any) {
    return Arg.is(arg => deepEqual(arg, expected));
  }
}
```

**Comment by Kosta-Github** [comment]
actually, the example from @MainAero works for me when defining return values, e.g.:
```TypeScript
import { Substitute, Arg } from '@fluffy-spoon/substitute';

import deepEqual from 'deep-equal';
function ArgIsDeep(expected: any) {
  return Arg.is(arg => deepEqual(arg, expected));
}

...
objMock.action(ArgIsDeep({ prop: "wow" })).returns('bla');
```
but not when validating like this:
```TypeScript
objMock.received().action(ArgIsDeep({ prop: "wow" }));
```
since `objMock.received().action()` expects only an argument of type `{ prop: string }` not an argument matcher...

**Comment by stephenh** [comment]
To chime in on this issue again, I'm trying to introduce FluffySpoon to a new project, and this bug bit us again on the very first test case. It's hard to push for FluffySpoon when such an obvious sharp edge exists, especially when IMO an easy/obvious fix exists (i.e. detect if the arg is an object literal and auto-deep-equal it).

```typescript
    const s = Substitute.for<{ send: (msg: { text: string }) => boolean }>();
    s.send({ text: "foo" }).returns(true);
    const r = s.send({ text: "foo" });
    console.log(r);
```

Console logs an anonyous function instead of `true`.

(Granted, I'm not talking about the `.received()` behavior here, just the regular setting up of mock behavior.)

**Comment by notanengineercom** [comment]
@ffMathy I think this issue can be closed now - seems like it was the issue described on #79

**Comment by ffMathy** [comment]
Thanks! Also, do you want to become an official contributor?

**Comment by notanengineercom** [comment]
Sure ^^ I am working on a few more contributions. Thanks for offering 😄

**Comment by ffMathy** [comment]
I added you now! Enjoy full rights to the repo 😁

And thanks once again for helping many users of this library.
