### ISSUE TITLE
Unable to chain received() and returns()

### ISSUE THREAD

**Issue by assapir** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#50]
Not sure if it is a bug or a feature request, but I think chaining like this:
```
mock.received(1).someMethod().returns({key: value)
```
should work.
currently it complains that:
```
Property 'returns' does not exist on type 'void'.ts(2339)
```

**Comment by ffMathy** [comment]
That's expected behavior. Make the two calls individually.
