### ISSUE TITLE
All functions shares the same state

### ISSUE THREAD

**Issue by renatomariscal** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#51]
Hi, I have the following test:
```typescript
interface Calculator {
    add(a: number, b: number): number;
    subtract(a: number, b: number): number;
    divide(a: number, b: number): number;
    isEnabled: boolean;
}

describe('calculator', () => {
    it('rejects non-called function', () => {
        const calculator = Substitute.for<Calculator>();
        calculator.add(1,2).returns(3);

        console.log(calculator.add(1,2));

        calculator.received().add(1,2);
        calculator.received().divide(1,2);
    });
});
```

Running on:
```
node       v10.7.0
ts-jest    24.0.2
ts-node    8.2.0
typescript 3.5.1
@fluffy-spoon/substitute 1.88.0
```

`add` and `divide` seems to be sharing the state, in that specific test I expected to get an error that divide wasn't called, but it passed.

If I change it to:
```typescript
        calculator.add(1,2).returns(3);

        console.log(calculator.add(1,2));

        calculator.received().divide(4,2);
```

I get the error:
```
    Expected 1 or more calls to the method add with arguments [4, 2], but received none of such calls.
    All calls received to method add:
    -> call with arguments [1, 2]
```

**Comment by ffMathy** [comment]
Thanks for the test, that'll at least prevent us from releasing something until this is fixed. I don't have much time these days though. Do you have time for a PR resolving it?

**Comment by renatomariscal** [comment]
I don't have much time either; I would need to spend some time getting familiar with the internals of it.
If I find time for it, I may get back.

**Comment by DanielSiepmann** [comment]
I guess this is the same issue as in #45?

**Comment by IlhamKhabibullin** [comment]
So this issue is fixed now, after merging this pr https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/pull/70
