### ISSUE TITLE
Automocking like in Nsubstitute

### ISSUE THREAD

**Issue by falconmick** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#54]
Hi!

Just wondering if this project plans to or can have support for an Nsubstitute feature in which the values returned themselves are also Nsubstitutes mocks. Or is this already a thing and I just am doing somthing wrong.

Cheers!

**Comment by ffMathy** [comment]
This can't be done unfortunately, because we don't know the return types of methods at runtime in JavaScript (typing information is lost in TypeScript when compiled too).

If that makes sense?
