### ISSUE TITLE
Minor issue in README.md

### ISSUE THREAD

**Issue by BillTriangle** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#58]
In the  [README under partial-mocks](https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking#partial-mocks)
 the return value should be -1 instead of 10:

`console.log(fakeCalculator.subtract(1, 2)); //prints -1`
instead of 
`console.log(fakeCalculator.subtract(1, 2)); //prints 10`

fakeCalculator use the real implementation of subtract

**Comment by ffMathy** [comment]
Fixed! Thanks.
