### ISSUE TITLE
Cannot mock function with optional parameters

### ISSUE THREAD

**Issue by chooban** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#59]
Apologies if I've missed this in the issues or readme.

If I attempt to create a mock which matches an optional parameter I get the error message of `Property 'returns' does not exist on type 'string'`.

e.g.

```typescript
interface IMyDoodad {
  maybeEcho(a?: string): string
}

test('it does not work if I provide the optional param', () => {
    const doodad = Substitute.for<IMyDoodad>()
    doodad.maybeEcho().returns('bar') // All good
    doodad.maybeEcho('foo').returns('bar') // Error
  })
```

I've created a small test case repo: https://github.com/chooban/substitute-optional

**Comment by ffMathy** [comment]
Nice - can you perhaps make a PR to this repo instead, with a test that reproduces it? :angel:

**Comment by chooban** [comment]
Sure! I'll make some time to get that done this afternoon.

**Comment by jamessawle** [comment]
A fix for this would be brilliant, as is causing me to fall back to jest.fn alot :(

**Comment by ffMathy** [comment]
Test has been merged in - thank you. Will look at fixing all tests soon.

**Comment by noelklein** [comment]
I'm having a similar problem with optional parameters and `received()`. Here's a PR to reproduce: #68
