### ISSUE TITLE
How to mock received function

### ISSUE THREAD

**Issue by Atagi** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#6]
As `received` function is part of `ObjectSubstitute` type how can I mock `received` function from my class?

**Comment by ffMathy** [comment]
You can't at the moment, but I'll work on an alternative syntax that will allow it.

It'll be ready in the weekend. 

Thank you for your report. 

For now as a workaround until then, rename your method to something else.

**Comment by ffMathy** [comment]
Actually, what happens if you try to do `fake.received().received(my-args-here);`?

**Comment by ffMathy** [comment]
This has now been resolved! A new version has been deployed, and documentation for how to get around it has been added to the repository documentation.

```typescript
class Example {
  received(someNumber: number) {
    console.log(someNumber);
  }
}

var fake = Substitute.for<Example>();

//BAD: this would have called substitute.js' "received" method.
//fake.received(2);

//GOOD: we now call the "received" method we have defined in the class above.
Substitute.disableFor(fake).received(1337);

//now we can assert that we received a call to the "received" method.
fake.received().received(1337);
```

**Comment by ffMathy** [comment]
Also note that there is full strong-typing all the way!
