### ISSUE TITLE
Feature request: fail when stub is called with arguments not maching any configured call.

### ISSUE THREAD

**Issue by pasku** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#62]
Currently, when I call a stub instance passing parameters which do not match any previously configured call, that call does not fail. It would be very useful if such a call would throw an error such as UnexpectedStubCall with details about the arguments mismatch.

This would be a breaking change, so it would probably need to be configured or used through a slightly different API.

What do you think about this?

**Comment by ffMathy** [comment]
This is not a feature in NSubstitute, which this library is a port of. I also don't see its broad use. Sorry.
