### ISSUE TITLE
Ability to mock that a function throws an Error

### ISSUE THREAD

**Issue by rodrigopsasaki** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#67]
I haven't found this anywhere and I feel like the library should handle this. I even looked at open and closed tickets but couldn't find this functionality.

I'd like to be able to have my mocked dependencies throw exceptions, for example:
```
const calculatorMock = Substitute.for<Calculator>();
calculatorMock.add(1, 1).throws(new Error('error message'))
```

Is there any reason why this is not supported?

**Comment by ffMathy** [comment]
Nope - just haven't implemented it. Feel free to make a PR!
