### ISSUE TITLE
Promise.resolve(aMockObject) return a Promise with pending status

### ISSUE THREAD

**Issue by luckymark** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#7]
I do something like this:
```js
let mockFooA = Substitute.for<FooA>()
let mockFooB = Substitute.for<FooB>()
mockFooB.fooFunction().returns(Promise.resolve(mockFooA))
```
I found Promise.resolve(mockFooA) will return a Promise with "pending" status.
Expected: "resolved"

when I use a Proxy instead of mockFooA like this:
```js
Promise.resolve(new Proxy({}, handler))
```
it return a Promise with "resolved" status as expected

thx!

**Comment by ffMathy** [comment]
Ah fine report indeed!

It seems the proxy is forwarding the promise "then" method and makes the browser believe the substitute itself is a proxy. 

Will find a workaround soon.

**Comment by joshribakoff** [comment]
Browser? Wouldn't this lib be exclusively for node env (jest, etc)? I have a similar issue where I want to spy on a method. Code coverage shows I called the method, but this lib sometimes says the method was not called. In some cases commenting out a previous `await` "fixes" the issue, still trying to narrow it down.

**Comment by joshribakoff** [comment]
My previous example may have been to be expected, but I think I have a valid one. Bottom line examples in the docs of how to do async mocking would be useful, 99% of the time im mocking its in an integration test that uses some kind of async logic like http/database, so working examples of promises would be invaluable. Sorry for comment spam, its been a long day.

```
test('test', async t=> {
	substitute.blocking().returns(Promise.resolve(undefined))

	// dont work
	async function service() {
		try {
		 await substitute.blocking()
		} catch(err) {
			console.log(err)
		}
	}
	await service()

	// works
	// substitute.blocking()
	
	substitute.received().blocking()
	t.is(456, 456)
})
```

gives

```
Joshs-MacBook-Pro-2:FluffySpoon.JavaScript.Testing.Faking joshribakoff$ yarn test
yarn run v1.7.0
$ tsc && ava

  15 passed
  1 failed

  test

  /Users/joshribakoff/FluffySpoon.JavaScript.Testing.Faking/src/Substitute.ts:376

   375:
   376:             throw new Error(errorMessa…
   377:         }

  Rejected promise returned by test. Reason:

  Error {
    message: `Expected one or more calls to the method blocking with no arguments, but received none of such calls.␊
    All calls received to method blocking: (nocalls)`,
  }

  Function.Substitute.assertCallMatchCount (src/Substitute.ts:376:19)
  Object.apply (src/Substitute.ts:77:26)
  spec/index.test.ts:67:24
  step (dist/spec/index.test.js:90:23)
  Object.next (dist/spec/index.test.js:57:20)
  fulfilled (dist/spec/index.test.js:24:32)
```

**Comment by joshribakoff** [comment]
Here is a valid workaround:

```
test('test', async t=> {
	const stub = sinon.fake.returns(Promise.resolve(42));
	substitute.blocking().mimicks(stub)
	async function service() {
		 return await substitute.blocking();
	}
	t.is((await service()), 42);
	t.truthy(stub.calledOnce)
})
```

**Comment by ffMathy** [comment]
I meant node, sorry. I'll take a look at it soon, I know what the cause is, and it is definitely fixable.

**Comment by ffMathy** [comment]
Hmmmm for the original issue, I made a test here which proves it does not fail: https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/commit/02245707e70b9d46ac3e9e6bb32c0c9b85795ccb

For the new issue, please report that separately.

**Comment by luckymark** [comment]
@ffMathy your test is different with this issue, Promise.resolve a nonmock object is ok,but resolve a mockObject it failed. 
Could you check it again ? thx!

**Comment by luckymark** [comment]
@ffMathy Now I found a temporal workround with Typemoq:
```js
let mockFooAService=TypeMoq.Mock.ofType(FooA)
let mockFooB = Substitute.for<FooB>()
mockFooB.fooFunction().returns(Promise.resolve(mockFooAService.object))
```

 I really really like your API , it's simple and elegant!  I love it!

**Comment by joshribakoff** [comment]
My favorite part is squashing the useless pedantry of mocks vs stubs vs spies. This library is pure genius.

**Comment by ffMathy** [comment]
Thank you so much guys! Please spread the word.
