### ISSUE TITLE
Working use case of `didNotReceive`?

### ISSUE THREAD

**Issue by shvgn** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#72]
I tried to use didNotReceive. Below are tests I ran in the repo. In the output, I get `Error: Test finished without running any assertions` for all these tests. I would like to know whether it simply does not work or I miss something.

```typescript
import test from "ava";

import { Substitute, Arg } from "../../src/index";

interface Calculator {
  add(a: number, b: number): number;
  subtract(a: number, b: number): number;
  divide(a: number, b: number): number;

  isEnabled: boolean;
}

test("check didNotReceive after not mocking and not calling a method", () => {
  const calculator = Substitute.for<Calculator>();

  // Do not mock and do not call

  calculator.didNotReceive().add(Arg.any(), Arg.any());
  calculator.didNotReceive().add(1, Arg.any());
  calculator.didNotReceive().add(1, 2);
});

test("check didNotReceive after not mocking but calling a method", () => {
  const calculator = Substitute.for<Calculator>();

  // Do not mock, but call
  calculator.add(1, 2);

  calculator.didNotReceive().add(Arg.any(), Arg.any());
  calculator.didNotReceive().add(1, Arg.any());
  calculator.didNotReceive().add(1, 2);
});

test("check didNotReceive after mocking but not calling a method", () => {
  const calculator = Substitute.for<Calculator>();

  // Mock but do not call
  calculator.add(1, 2).returns(3);

  calculator.didNotReceive().add(Arg.any(), Arg.any());
  calculator.didNotReceive().add(1, Arg.any());
  calculator.didNotReceive().add(1, 2);
});

test("check didNotReceive after mocking and calling a method", () => {
  const calculator = Substitute.for<Calculator>();

  // Mock and call
  calculator.add(1, 2).returns(3);
  calculator.add(1, 2);

  calculator.didNotReceive().add(Arg.any(), Arg.any());
  calculator.didNotReceive().add(1, Arg.any());
  calculator.didNotReceive().add(1, 2);
});
```

Output: 

```
npm test spec/issues/didNotReceive.test.ts

> @fluffy-spoon/substitute@1.0.0 test /Users/shvgn/dev/FluffySpoon.JavaScript.Testing.Faking
> tsc && ava "spec/issues/didNotReceive.test.ts"



  4 tests failed

  check didNotReceive after not mocking and not calling a method


  Error: Test finished without running any assertions



  check didNotReceive after not mocking but calling a method


  Error: Test finished without running any assertions



  check didNotReceive after mocking but not calling a method


  Error: Test finished without running any assertions



  check didNotReceive after mocking and calling a method


  Error: Test finished without running any assertions

npm ERR! Test failed.  See above for more details.
```

**Comment by shvgn** [comment]
Made PR with these tests #73 in case they are useful.

**Comment by ffMathy** [comment]
You're actually doing it entirely right.

Ava is just complaining that you don't have any assertions.

substitute.js doesn't know anything about AVA. That's why it doesn't call any assertions in AVA either.

You can ask AVA to allow tests with no assertions, or use  "t.pass();" in your test.

Does that help?

**Comment by shvgn** [comment]
Thanks, I get it with Ava. 

What confuses me is that none of this tests failed. I expected 2nd or 4th to fail, where actual call happens: `calculator.add(1, 2)`. We call a method, than verify with `didNotReceive` that is was not called. And in fact nothing happens.

**Comment by ffMathy** [comment]
Ah I see. Can you change the tests to include "t.pass" and then I will re-introduce them?

**Comment by shvgn** [comment]
A did add `t.pass()`, but still get ` Error: Test finished without running any assertions`

**Comment by wschurman** [comment]
After looking at the code, I believe that `didNotReceive` isn't implemented? I only see a property case for `received`: https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/blob/master/src/states/InitialState.ts#L138

**Comment by shvgn** [comment]
I saw that too. I used `received(0)` in my tests.

**Comment by wschurman** [comment]
I'm working on a PR to alias it, though some complex situations arise for some of the test cases you provided that should throw. We'll see how far I get.
