### ISSUE TITLE
mock with a private field failed

### ISSUE THREAD

**Issue by luckymark** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#8]
when I do this:
```js
class Foo { 
    private field: string
}
let mock: Foo = Substitute.for<Foo>()
```
I get ：error TS2322: Type 'ObjectSubstitute<Pick<Foo, never>, Foo>' is not assignable to type 'Foo'.
  Property 'field' is missing in type 'ObjectSubstitute<Pick<Foo, never>, Foo>'.

when I change "private" to "public", its ok!

**Comment by ffMathy** [comment]
What is the use case for this?

Why do you have a class only with private fields that you want to mock? 

You should only test publically exposed functionality.

**Comment by joshribakoff** [comment]
> Why do you have a class only with private fields that you want to mock?

He doesn't. He distilled the example, to simplify it for us.

> You should only test publically exposed functionality.

Thats what hes trying to do...
```ts

class Foo { 
	private field: string
	public bar() {}
}
let mock: Foo = Substitute.for<Foo>() // error TS2322: 
```

The problem is he typed the mock to Foo, use the provided generic or let TS infer & it works fine:

```ts
ObjectSubstitute<OmitProxyMethods<Example>, Example>;
```

User error.

**Comment by luckymark** [comment]
@joshribakoff yes，I just simplify the test case！
In my use case, maybe I have a class :
```js
class A{
   public needMock:Foo
}
```
the field needMock will be injected by some other code...

**Comment by ffMathy** [comment]
Ah I see! Yes, that should be resolved as soon as possible!

I'll look into it sometime next week, as I am quite busy lately. 

In the meanwhile, PRs are welcome!

**Comment by ffMathy** [comment]
I made a branch now called `progress` where I am refactoring the whole thing into being based on a strategy pattern.

You can follow up on the progress there. However, I don't have much time lately. Feel free to fork that branch and continue.

**Comment by ffMathy** [comment]
We can't fix this without breaking other things, until this feature is implemented:

https://github.com/Microsoft/TypeScript/issues/22677

**Comment by ilancohen** [comment]
@ffMathy - I really like this library, but without this fixed, using this library for Angular with its dependency injection is basically a non-starter. For instance, I have a class that depends on a service that I want to mock:

```
@Injectable({
  providedIn: "root"
})
export class LocaleService {
  constructor(private translate: TranslateService) {
  }

  getLocale() {
    return {};
  }

  getSupportedLocales(): any[] {
    return {};
  }
}
```

Mocking LocaleService (for usage in initializing your class) will throw a TS error, since `translate` is not defined.

Any suggestions? I'm happy to help fix this with a pull request, if you have a suggestion.

**Comment by ffMathy** [comment]
Can you provide a minimal example to reproduce it? Perhaps a PR that adds a unit test or similar? Or a separate project that demonstrates the problem?

**Comment by ilancohen** [comment]
I haven't tested it, but I think the code below provides a minimal example.
In this scenario, we're trying to mock `ClassB` to test `ClassC`:

```typescript
class ClassA {
	constructor(){}

	methodA(): string {
		return 'abc'
	}
}

class ClassB {
	constructor(
		private classA: ClassA
	) {}

	methodB(): string {
		return this.classA.methodA();
	}

	methodB2(): string {
		return 'def'
	}
}

class ClassC {
	constructor(
		private classB: ClassB
	) {}

	methodC(): string {
		return this.classB.methodB2();
	}
}

const classBMock = Substitute.for<ClassB>();
const classC = new ClassC(classBMock);
```

Typescript will complain about that last line because `classBMock` lacks a member called `classA`.

**Comment by ffMathy** [comment]
Will investigate soon!

**Comment by ilancohen** [comment]
@ffMathy - I created a [basic example](https://www.typescriptlang.org/play/#src=class%20AllArguments%20extends%20Argument%3Cany%3E%20%7B%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20super('%7Ball%7D'%2C%20()%20%3D%3E%20true)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Atype%20NoArgumentFunctionSubstitute%3CTReturnType%3E%20%3D%20%0D%0A%20%20%20%20(()%20%3D%3E%20(TReturnType%20%26%20NoArgumentMockObjectMixin%3CTReturnType%3E))%0D%0A%0D%0Atype%20FunctionSubstitute%3CTArguments%20extends%20any%5B%5D%2C%20TReturnType%3E%20%3D%20%0D%0A%20%20%20%20((...args%3A%20TArguments)%20%3D%3E%20(TReturnType%20%26%20MockObjectMixin%3CTArguments%2C%20TReturnType%3E))%20%26%20%0D%0A%20%20%20%20((allArguments%3A%20AllArguments)%20%3D%3E%20(TReturnType%20%26%20MockObjectMixin%3CTArguments%2C%20TReturnType%3E))%0D%0A%0D%0Atype%20PropertySubstitute%3CTReturnType%3E%20%3D%20(TReturnType%20%26%20Partial%3CNoArgumentMockObjectMixin%3CTReturnType%3E%3E)%3B%0D%0A%0D%0Atype%20BaseMockObjectMixin%3CTReturnType%3E%20%3D%20%7B%0D%0A%20%20%20%20returns%3A%20(...args%3A%20TReturnType%5B%5D)%20%3D%3E%20void%3B%0D%0A%7D%0D%0A%0D%0Atype%20NoArgumentMockObjectMixin%3CTReturnType%3E%20%3D%20BaseMockObjectMixin%3CTReturnType%3E%20%26%20%7B%0D%0A%20%20%20%20mimicks%3A%20(func%3A%20()%20%3D%3E%20TReturnType)%20%3D%3E%20void%3B%0D%0A%7D%0D%0A%0D%0Atype%20MockObjectMixin%3CTArguments%20extends%20any%5B%5D%2C%20TReturnType%3E%20%3D%20BaseMockObjectMixin%3CTReturnType%3E%20%26%20%7B%0D%0A%20%20%20%20mimicks%3A%20(func%3A%20(...args%3A%20TArguments)%20%3D%3E%20TReturnType)%20%3D%3E%20void%3B%0D%0A%7D%0D%0A%0D%0Atype%20ObjectSubstitute%3CT%20extends%20Object%2C%20K%20extends%20Object%20%3D%20T%3E%20%3D%20ObjectSubstituteTransformation%3CT%3E%20%26%20%7B%0D%0A%20%20%20%20received(amount%3F%3A%20number)%3A%20TerminatingObject%3CK%3E%3B%0D%0A%20%20%20%20didNotReceive(amount%3F%3A%20number)%3A%20TerminatingObject%3CK%3E%3B%0D%0A%20%20%20%20mimick(instance%3A%20T)%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Atype%20TerminatingObject%3CT%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20T%5D%3A%0D%0A%20%20%20%20T%5BP%5D%20extends%20()%20%3D%3E%20infer%20R%20%3F%20()%20%3D%3E%20void%20%3A%0D%0A%20%20%20%20T%5BP%5D%20extends%20(...args%3A%20infer%20F)%20%3D%3E%20infer%20R%20%3F%20(...args%3A%20F)%20%3D%3E%20void%20%3A%20%0D%0A%20%20%20%20T%5BP%5D%3B%0D%0A%7D%0D%0A%0D%0Atype%20ObjectSubstituteTransformation%3CT%20extends%20Object%3E%20%3D%20%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20T%5D%3A%0D%0A%20%20%20%20T%5BP%5D%20extends%20()%20%3D%3E%20infer%20R%20%3F%20NoArgumentFunctionSubstitute%3CR%3E%20%3A%0D%0A%20%20%20%20T%5BP%5D%20extends%20(...args%3A%20infer%20F)%20%3D%3E%20infer%20R%20%3F%20FunctionSubstitute%3CF%2C%20R%3E%20%3A%0D%0A%20%20%20%20PropertySubstitute%3CT%5BP%5D%3E%3B%0D%0A%7D%0D%0A%0D%0Atype%20Omit%3CT%2C%20K%20extends%20keyof%20T%3E%20%3D%20Pick%3CT%2C%20Exclude%3Ckeyof%20T%2C%20K%3E%3E%3B%0D%0A%0D%0Aexport%20type%20OmitProxyMethods%3CT%20extends%20any%3E%20%3D%20Omit%3CT%2C%20'mimick'%7C'received'%7C'didNotReceive'%3E%3B%0D%0A%0D%0Aexport%20type%20DisabledSubstituteObject%3CT%3E%20%3D%20T%20extends%20ObjectSubstitute%3COmitProxyMethods%3Cinfer%20K%3E%2C%20infer%20K%3E%20%3F%20K%20%3A%20never%3B%0D%0A%0D%0Aclass%20ClassA%20%7B%0D%0A%09constructor()%7B%7D%0D%0A%0D%0A%09methodA()%3A%20string%20%7B%0D%0A%09%09return%20'abc'%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aclass%20ClassB%20%7B%0D%0A%09constructor(%0D%0A%09%09private%20classA%3A%20ClassA%0D%0A%09)%20%7B%7D%0D%0A%0D%0A%09methodB()%3A%20string%20%7B%0D%0A%09%09return%20this.classA.methodA()%3B%0D%0A%09%7D%0D%0A%0D%0A%09methodB2()%3A%20string%20%7B%0D%0A%09%09return%20'def'%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aclass%20ClassC%20%7B%0D%0A%09constructor(%0D%0A%09%09private%20classB%3A%20ClassB%0D%0A%09)%20%7B%7D%0D%0A%0D%0A%09methodC()%3A%20string%20%7B%0D%0A%09%09return%20this.classB.methodB2()%3B%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Aconst%20classBMock%20%3D%20%3CObjectSubstitute%20%3C%20OmitProxyMethods%20%3CClassB%3E%2C%20ClassB%3E%3E%20%7B%7D%3B%0D%0Aconst%20classC%20%3D%20new%20ClassC(classBMock)%3B), using your code.

**Comment by ffMathy** [comment]
Fixed. Thanks for making the library better!
