### ISSUE TITLE
Can't mock method that returns boolean

### ISSUE THREAD

**Issue by xamoulin** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#86]
When I try to setup the return value for a method that returns a boolean I have the following error: Argument of type 'true' is not assignable to parameter of type 'never'.

It was working fine in version 1.112.0 but it's broken in 1.116.0.

**Comment by ffMathy** [comment]
@notanengineercom I'm baffled by this, and have no idea of the root cause. Could it be the new Promise features?

**Comment by notanengineercom** [comment]
Just tested it, and confirmed. It's something to do with the new typings (T extends Promise...). Weirdly enough, only happens with booleans. All other return types are not affected. We'll take a look this evening. As a note, we need to make extensive tests for each substitute method, where we test all possible types!
