### ISSUE TITLE
Returns is possibly undefined on property

### ISSUE THREAD

**Issue by xamoulin** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#87]
When I try to setup a return value for a property, `returns` is detected as possibly undefined.

`const something = Substitute.for<Something>();`
 `something.isSomething.returns(true);`

It can be workaround by doing : `something.isSomething.returns!(true);`

**Comment by notanengineercom** [comment]
Related to #86

**Comment by xamoulin** [comment]
@notanengineercom I don't think this is related to #86 because I had this issue in version 1.112.0 and it's still there in 1.116.0. Also it's not only with boolean type, it's with all properties.

**Comment by notanengineercom** [comment]
You are right, it's because of the `Partial<T>` on this line: https://github.com/ffMathy/FluffySpoon.JavaScript.Testing.Faking/blob/c21c4cbbd09e9205bc0d69a5b86cc0b6599200f8/src/Transformations.ts#L15

**Comment by ffMathy** [comment]
Hmmm interesting - does that mean we can't fix it due to a TypeScript limitation?
