### ISSUE TITLE
Can I mock a listener receiving a callback

### ISSUE THREAD

**Issue by bachstatter** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#89]
Thanks for an awesome library!
Is there anyway to mock the monitor function and call that with values to assert?
```
Interface Device{
    monitor(
      listener: (error: Error, data: data) => void,
    ): Unsubscrbe
}
```

**Comment by ffMathy** [comment]
Yeah, look at `Arg.is`, under "Matching specific arguments" in the README 👍 

If you like the library, consider sponsoring as well via the "sponsor" button.
