### ISSUE TITLE
Infinite recursion in deepEqual

### ISSUE THREAD

**Issue by stephenh** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#90]
`deepEqual` doesn't handle objects that have cyclical references:

```typescript
import { Substitute } from "@fluffy-spoon/substitute";

interface Service {
  foo(a: any): void;
}

describe("Service", () => {
  it("overflows", async () => {
    const s = Substitute.for<Service>();

    const parent = {} as any;
    parent.child = { parent };

    s.foo(parent);
    s.foo(parent);
  });
});
```

```
RangeError: Maximum call stack size exceeded

    at deepEqual (/home/stephen/homebound/graphql-service/node_modules/@fluffy-spoon/substitute/src/Utilities.ts:76:19)
    at deepEqual (/home/stephen/homebound/graphql-service/node_modules/@fluffy-spoon/substitute/src/Utilities.ts:95:2)
    at deepEqual (/home/stephen/homebound/graphql-service/node_modules/@fluffy-spoon/substitute/src/Utilities.ts:95:2)
    at deepEqual (/home/stephen/homebound/graphql-service/node_modules/@fluffy-spoon/substitute/src/Utilities.ts:95:2)
    at deepEqual (/home/stephen/homebound/graphql-service/node_modules/@fluffy-spoon/substitute/src/Utilities.ts:95:2)
 ```

**Comment by notanengineercom** [comment]
Good catch!
I think using `Arg.is()` will work for objects with circular references

```ts
s.foo(Arg.is((input) => input.propA === 'propA' )).returns|throws|resolves...
```

**Comment by stephenh** [comment]
@notanengineercom yeah, that is a work around, but if my service has, say 10 methods, and my test only wants to mock one of them, I have to write this ^ snippet for all the other 9 methods, and do it for every test, and every time I add a new "oh write this argument has cycles" method, update all the tests (or make a central helper method that says "create this mock but without the cyclic error bug for its parameters).

I.e. I'll push that really `deepEquals` needs to be fixed to detect cycles.

**Comment by ffMathy** [comment]
I think `deepEqual` should contain an array of object references it has seen before "locally". If it stumbles upon one that it has seen before, it just compares against `undefined`.

What do you think of that @notanengineercom?

**Comment by notanengineercom** [comment]
> I think deepEqual should contain an array of object references it has seen before "locally". 

Yes, that sounds good to me @ffMathy

**Comment by ffMathy** [comment]
Perfect. I'll see if I have time over the next upcoming weeks :+1:

**Comment by notanengineercom** [comment]
@ffMathy if you don't find the time, let me know. Due to the current state of the wold I have a few more hours of free time 😄

**Comment by ffMathy** [comment]
Haha yeah okay - feel free to begin then! <3
