### ISSUE TITLE
resolve() without an argument does not return a promise

### ISSUE THREAD

**Issue by vigie** [ffMathy/FluffySpoon.JavaScript.Testing.Faking#92]
Hi

Thanks for the library, great syntax. Just tried incorporating it today and noticed the following:

```
const result = mySubstitute.myPromise().resolves();
```

`result` should be a Promise but it is `undefined`.

To make this work, currently need to write

```
const result = mySub.myPromise().resolves(undefined);
```

**Comment by notanengineercom** [comment]
Good catch! I could reproduce the isssue, and I'm pushing a fix 😄
